### ISSUE TITLE
Link Borrower in book info to their profile

### ISSUE THREAD

**Issue by AY-Chen** [CMPUT301W19T11/Atheneum#113]
Not completed yet. Should be fairly quick to do.
Outcome should be:
If there is a borrower attached to a book, clicking the borrower username(email)/picture area should open the activity containing their profile.

**Comment by ishchow** [comment]
US 02.03.01
As an owner or borrower, I want to retrieve and show the profile of a presented username.

**Comment by MarcusBoay** [comment]
Related:
If there are requesters for a book, clicking their area should give the user's profile.
