### ISSUE TITLE
Book ISBN Scanning to Checkout and Return a Book

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#129]
Borrowing

US 06.01.01
As an owner, I want to hand over a book by scanning the book ISBN code and denoting the book as borrowed.

US 06.02.01
As a borrower, I want to receive an accepted book by scanning the book ISBN code to confirm I have borrowed it.

US 06.03.01
As a borrower, I want to view a list of books I am borrowing, each book with its description and owner username. 

Returning

US 07.01.01
As a borrower, I want to hand over a book I borrowed by scanning the book ISBN code to denote the book as available.

US 07.02.01
As an owner, I want to receive a returned book by scanning the book ISBN code to confirm I have it available.

**Comment by ishchow** [comment]
@Kaho-Lee Take 6.3

**Comment by siyuamymi** [comment]
Completed, closing this issue.
