### ISSUE TITLE
Change book status as we do things in the app

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#131]
US 01.03.01
As an owner or borrower, I want a book to have a status of one of: available, requested, accepted, or borrowed.

This won't be done by one person but as part of separate features

**Comment by MarcusBoay** [comment]
Status change to accepted done in #143

**Comment by Kaho-Lee** [comment]
Status change to 'REQUESTED' when a new request is generated. finished at #153

**Comment by ishchow** [comment]
@MarcusBoay @Kaho-Lee this seems to be done. Is there anything left to do for this? If not, can one of you close this issue? Thanks.

**Comment by MarcusBoay** [comment]
I think it's done

**Comment by MarcusBoay** [comment]
Just to be sure, @siyuamymi

**Comment by siyuamymi** [comment]
Yeah this should be done
