### ISSUE TITLE
Requests on a book doesn't show up sometimes

### ISSUE THREAD

**Issue by MarcusBoay** [CMPUT301W19T11/Atheneum#144]
Requests on a book doesn't show up for the first few times. Access any book that has requests from your owner page.

**Comment by Kaho-Lee** [comment]
I did see the similar problem. Boy it might be because the inconsistency in our database.
Most of book request work well. And I only see the same problem one time when I made random requests in this afternoon.

**Comment by ishchow** [comment]
@Kaho-Lee @MarcusBoay this done?

**Comment by MarcusBoay** [comment]
No clue

**Comment by Kaho-Lee** [comment]
It is done. I haven’t seen this error in our  newest version of app.


在 2019年3月31日，下午4:31，Marcus Boay <notifications@github.com<mailto:notifications@github.com>> 写道：


No clue
