### ISSUE TITLE
Add notifications to home page

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#160]
**Is your feature request related to a problem? Please describe.**
Vinay wanted us to have a single place on our app where our notifications would reside outside of push notifications. Sort of like the Facebook notifications where they are chronological and appear in one page. Can also have inbox-like features such as swipe to delete.

**Describe the solution you'd like**
Have the notifications appear as a list on the home page. Swiping a notification should delete it. Clicking a notification should take you to the relevant page in the app (usually go to book info activity).

We can have a separate table in our database for inapp notifications that is written to when we create/accept requests etc so that we can persist notifications.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MarcusBoay** [comment]
Do we still want to add notifications to the home page??

**Comment by ishchow** [comment]
@MarcusBoay nah, that's fine. I kind of like the notifications being a separate activity better. You can close this. We can just leave the Home fragment blank for now.
