### ISSUE TITLE
Have notifications spawn relevant activites/UI components

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#161]
**Is your feature request related to a problem? Please describe.**
Vinay mentioned that he would like notifications to take you to the relevant activity when clicked. For example, when an owner receives a notification that someone has requested their book, clicking the notification should take the owner to the book info activity.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by MarcusBoay** [comment]
I think this is done
