### ISSUE TITLE
Clear all notifications from notification activity

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#207]
**Is your feature request related to a problem? Please describe.**
I have too many notifications on my screen and I want to be able to either clear all of them or only see the first X of them to keep it manageable.

**Describe the solution you'd like**
I think it would be best if there was a menu option in the toolbar that would clear all the notifications for you. Look at the BookInfoActivity where we have the buttons for editing and deleting the book for reference.

**Describe alternatives you've considered**
You can also modify the database query for showing notifications to only limit to the first X.

**Additional context**
This is what my notifications looks like now lol:
![Screenshot_2019-03-18-11-39-45-315](https://user-images.githubusercontent.com/15524738/55295976-8a4b3b80-53d0-11e9-9846-167fbe5487ce.jpeg)

**Comment by MarcusBoay** [comment]
The screenshot provided isn't notifications.

**Comment by ishchow** [comment]
Actual screenshot (the above was wrong):

![Screenshot_2019-03-31-16-13-39](https://user-images.githubusercontent.com/15524738/55295989-b5358f80-53d0-11e9-9c1c-2da542f42dc2.jpg)

**Comment by ishchow** [comment]
I got spammed a bunch of notifications over the weekend which I kind of ignored because they became a bit too much

**Comment by MarcusBoay** [comment]
I'm getting different features being requested here.
Do we want a menu option for the user to delete all notifications or make all notifications seen?
OR
Do we want to limit the number of notifications being loaded in NotificationsAcitivty onCreate? If so, do we want a feature for an infinitely scrolling list where notifications are loaded in dynamically when the user scrolls all the way to the bottom?

**Comment by MarcusBoay** [comment]
Getting spammed a bunch of notifications has to do with the service and not the NotificationsActivity. This would be a separate feature

**Comment by ishchow** [comment]
@MarcusBoay I think it would be best if there was a menu option that would delete all the notifications so that they can be cleared. That should be pretty simple to do. The infinitely scrolling list might be a bit too fancy.

Getting spam is not a bug it's just that people were making a lot of requests on my books and it was kind of overwhelming and I didn't have time to clean the notifications page. This isn't a super high priority thing but it would be nice if we had this for the demo so we can present a more clean notifications page.

**Comment by MarcusBoay** [comment]
Ok
