### ISSUE TITLE
Create Initial UML Diagram

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#3]

**Comment by AY-Chen** [comment]
Pretty much finished. Someone should check over before we close this. Link to diagram is https://www.lucidchart.com/documents/edit/9d790e9d-1a96-48ff-92c6-aeac86bb69d8/0?shared=true&
If you can't see it we'll add you somehow.

**Comment by AY-Chen** [comment]
Uploaded UML to a new wiki page: 
https://github.com/CMPUT301W19T11/Atheneum/wiki/UML-Class-Diagrams
