### ISSUE TITLE
Adding new book as owner produces duplicates in Firebase

### ISSUE THREAD

**Issue by MarcusBoay** [CMPUT301W19T11/Atheneum#48]
Adding a new book as an owner can produce duplicates in Firebase

How to reproduce:
1. Go to add book
2. Fill in fields
3. Hit save floating action button multiple times

**Comment by ishchow** [comment]
I haven't had time to try to reproduce this but one way you could fix it would be to make the save floating action button clickable after the OnClickListener is executed

**Comment by ishchow** [comment]
This bug might impact our other forms that we use so we should definitely fix this for part 5
