### ISSUE TITLE
Add Book Search

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#55]
US 03.01.01

US 03.02.01

I think it makes sense to pull in a fragment/search activity to search for books in this part in order to make requesting easier.

**Comment by ishchow** [comment]
@Kaho-Lee Can you do this after I merge my PR to change the owner collection? That PR will make searching for books easier.

After that PR goes through, can you change the BorrowerPragment to have a floating action button with a search bar that goes to a new activity to do the searching. You can look at what Sam has done for search. Then in the search activity, you can click on it to view info for a book.

**Comment by Kaho-Lee** [comment]
> @Kaho-Lee Can you do this after I merge my PR to change the owner collection? That PR will make searching for books easier.
> 
> After that PR goes through, can you change the BorrowerPragment to have a floating action button with a search bar that goes to a new activity to do the searching. You can look at what Sam has done for search. Then in the search activity, you can click on it to view info for a book.

Sure, I can do these two parts.

**Comment by Kaho-Lee** [comment]
> > @Kaho-Lee Can you do this after I merge my PR to change the owner collection? That PR will make searching for books easier.
> > After that PR goes through, can you change the BorrowerPragment to have a floating action button with a search bar that goes to a new activity to do the searching. You can look at what Sam has done for search. Then in the search activity, you can click on it to view info for a book.
> 
> Sure, I can do these two parts.

**Comment by Kaho-Lee** [comment]
> > @Kaho-Lee Can you do this after I merge my PR to change the owner collection? That PR will make searching for books easier.
> > After that PR goes through, can you change the BorrowerPragment to have a floating action button with a search bar that goes to a new activity to do the searching. You can look at what Sam has done for search. Then in the search activity, you can click on it to view info for a book.
> 
> Sure, I can do these two parts.

**Comment by ishchow** [comment]
@Kaho-Lee is this done? I thought you did this as part of #92?

**Comment by Kaho-Lee** [comment]
> @Kaho-Lee is this done? I thought you did this as part of #92?

I have done the floating button to go to a new activity to do search. But I forgot to implement the book info part. Focused too much on the crash and display issues. I would try to implement it tonight. And If it goes well, I would upload it. Otherwise, it is very likely that I would leave it in my own branch and keep it for part 5.

**Comment by ishchow** [comment]
@Kaho-Lee we talked about this on slack but since the book info part isn't technically part of the user stories 3.01.01 and 3.02.01, I'm going to close this. The book info can be added in a different PR when implementing 5.4.1
