### ISSUE TITLE
Phone's back button pressed when in edit profile activity doesn't remove old content

### ISSUE THREAD

**Issue by MarcusBoay** [CMPUT301W19T11/Atheneum#67]
When the user is on the edit profile page, pressing the back button returns the user to the home page. However, the edit profile view is overlayed on top of the home page view.

How to reproduce:
1. Go to Profile from side drawer
2. Tap on edit profile floating action button
3. Hit your phone's back button

**Comment by AY-Chen** [comment]
IMO the edit profile should be an activity too, and not a fragment. That would resolve this issue too.
