### ISSUE TITLE
Fix test cases

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#81]
Test Cases:
Provide unit tests for your model classes. Provide intent tests for the requirements you support. Deliver the test code to your source repository. If you have test data files, also include those. Test data should be realistic.

Remove owner and borrower collection

**Comment by MarcusBoay** [comment]
I fixed NotificationTest on my branch to accommodate for the new change in the Notifications class

**Comment by Kaho-Lee** [comment]
I have fixed the test cases of book and request, which can be seen when merging #92 with master.
