### ISSUE TITLE
Create a Wiki Page for Firebase Schema

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#84]
Have current schema and have notes on the top with proposed changes

**Comment by AY-Chen** [comment]
Done. Take a look and lmk if there's something to change or add(esp for proposed changes) 
Otherwise I will close this issue.

**Comment by AY-Chen** [comment]
Ishaat made changes to elaborate on schema change proposals. 
Closing issue, wiki page should be done for now, but it will need to be updated as we proceed.
