### ISSUE TITLE
Add UI tests

### ISSUE THREAD

**Issue by ishchow** [CMPUT301W19T11/Atheneum#87]
Provide intent tests for the requirements you support. Deliver the test code to your source repository. If you have test data files, also include those. Test data should be realistic.

**Comment by ishchow** [comment]
I can write UI tests for registration

**Comment by siyuamymi** [comment]
I can write the UI tests for the books

**Comment by AY-Chen** [comment]
@siyuamymi what part of the books? I was planning to do that but I can do something else instead

**Comment by siyuamymi** [comment]
I'm just starting now so if you've already started, I can do something else like maybe profiles

**Comment by AY-Chen** [comment]
Yeah, I already started a bit. I should have said something

If you could do profiles that would be great ^^

**Comment by siyuamymi** [comment]
No prob, ill do profile rn

**Comment by Kaho-Lee** [comment]
I can write UI test for the borrower section.

**Comment by ishchow** [comment]
#101 partially completes this

**Comment by ishchow** [comment]
Honestly, I think that we should only have UI tests for adding/viewing/deleting books as well as viewing/editing the profile since those are fairly self contained. @Kaho-Lee @MarcusBoay  We should not have UI tests for requests/borrowing since they require you to make requests on books that are already in the database. It would be hard to make those tests very repeatable and accurate since they depend on other data in a live production instance.

**Comment by ishchow** [comment]
Looking at some past projects, they didn't have many UI tests so I don't think we should worry about them too much. I think signin/book/profile tests should be good enough.

**Comment by ishchow** [comment]
I think we have enough UI tests for this part. I'm going to close this issue.
