### ISSUE TITLE
Profile still shows old content after editing

### ISSUE THREAD

**Issue by siyuamymi** [CMPUT301W19T11/Atheneum#89]
To reproduce:
1. go the profile and click edit button
2. edit something and press save

**Comment by ishchow** [comment]
@siyuamymi Is this just the view profile page or also the picture in the navbar?

**Comment by ishchow** [comment]
If it's just in the view profile page, then this could be fixed by sending the userID to the ViewProfileFragment and then querying the user in the ViewProfileFragment.

**Comment by siyuamymi** [comment]
Its just the profile page, i will fix this later.
