### ISSUE TITLE
App crashes after auto-populate from isbn

### ISSUE THREAD

**Issue by siyuamymi** [CMPUT301W19T11/Atheneum#98]
To reproduce:
1. From owner page, either click on a book and press edit, or create a new book.
2. Enter in ISBN and press auto-populate button.
3. Save book
4. From nav drawer, go somewhere else

**Comment by ishchow** [comment]
I can't seem to reproduce this on master

**Comment by siyuamymi** [comment]
Hmm, this is weird, repulled from master and now it seems to be fine. I will close this issue then.
